-- ASCII
SELECT ASCII('Ğ')
SELECT ASCII(CHAR(49))
SELECT CHAR(ASCII('Ö'))

-- SUBSTRING
SELECT SUBSTRING('EGEMEN EROGLU',1,6)

SELECT * FROM USER_ WHERE USERNAME_ LIKE 'E%' -- DEMEK YERİNE
SELECT * FROM USER_ WHERE SUBSTRING(USERNAME_1,1)='E' -- YAPABİLİRİZ

-- CHARINDEX
SELECT CHARINDEX('E','EGEMEN EROĞLU',1) -- İLK GÖRDÜĞÜ İNDEXİ SÖYLER
SELECT CHARINDEX('EROĞLU','EGEMEN EROĞLU',1)

-- CONCAT
SELECT 'EGEMEN' + ' ' + 'EROĞLU' -- YERİNE
SELECT CONCAT('EGEMEN',' ','EROĞLU') -- YAPABİLİRİZ
SELECT CONCAT_WS('_','EGEMEN','EROĞLU') -- CONCAT WITH SEPERATOR

-- FORMAT
SELECT FORMAT(GETDATE(),'d','en-us')
SELECT FORMAT(GETDATE(),'D','en-us')

SELECT FORMAT(GETDATE(),'d','de-de')

-- LEFT, RIGHT, LEN
SELECT LEFT('EGEMEN EROĞLU',6)
SELECT RIGHT('EGEMEN EROĞLU',6)
SELECT LEN('EGEMEN')

-- TRIM, LTRIM, RTRIM

SELECT TRIM(' EGEMEN EROĞLU ')
SELECT LTRIM(' EGEMEN EROĞLU ')
SELECT RTRIM(' EGEMEN EROĞLU ')

--  LOWER, UPPER, REVERSE, REPLICATE, REPLACE

SELECT UPPER('Egemen')
SELECT LOWER('Egemen')
SELECT REVERSE('Egemen')
SELECT REPLICATE('0',10)
SELECT REPLACE('EGEMEN EROĞLU','EGEMEN','Egemen')

-- DEĞİŞKEN TANIMLAMA

DECLARE @ISIM AS VARCHAR(20)
SET @ISIM = 'EGEMEN'
SELECT @ISIM