SELECT
	U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,
	CT.CITY AS IL, T.TOWN AS ILCE, D.DISTRICT AS SEMT, A.ADDRESSTEXT AS ACIKADRES,
	O.ID AS SIPARISID,O.DATE_ AS TARIH,O.TOTALPRICE AS TOPLAMTUTAR,
	P.DATE_ AS ODEMETARIHI,P.APPROVECODE AS BANKAONAYKODU,
	I.DATE_ AS FATURATARIHI,I.CARGOFICHENO AS KARGOFISNO,
	ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI,
	OD.AMOUNT AS MIKTAR, OD.UNITPRICE AS BIRIMFIYAT, OD.LINETOTAL AS SATIRTOPLAMI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
WHERE 
--U.NAMESURNAME = 'Ceyda GEZGİNCİ'
O.ID = 3515

------------------------------------------------------------

-- ŞEHİRLERE GÖRE TOPLAM VERİLEN SİPARİŞ MİKTARI
SELECT
	CT.CITY AS SEHIRADI,
	SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
	COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

GROUP BY CT.CITY
-- ORDER BY CT.CITY -- A-Z Şehirler
ORDER BY SUM(OD.LINETOTAL) DESC -- En çok sipariş verilen

------------------------------------------------------------

-- ÜRÜN KATEGORİLERİNE GÖRE SİPARİŞ DAĞILIMI
SELECT
	ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,
	SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
	COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI,
	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYAT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

WHERE ITM.CATEGORY1='EV'
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3
ORDER BY 4 DESC
------------------------------------------------------------

-- ÜRÜNLERİN FİYAT ANALİZİ, EN ÇOK HANGİ AY SATILDI

SET STATISTICS IO ON
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(SELECT SUM(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET,
(
SELECT TOP 1 DATEPART(MONTH, O.DATE_) AS AY FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
WHERE OD.ITEMID = ITM.ID
GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC
) AS ENCOKSATILANAY

FROM
ITEMS ITM

WHERE ITEMCODE IN ('10740','11396')

ORDER BY 3

-- KULLANICININ SON ADRESİNİ BULMA
SELECT U.*,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID DESC) SONADRES
FROM USERS U
WHERE U.ID=1

SELECT * FROM USERS