/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (20) [Branch_Code]
      ,[Branch_Name]
      ,[Branch_Type]
      ,[Service_Model]
      ,[isClosed]
      ,[isSatellite]
      ,[Queue_Wait_Time_mins]
      ,[Queue_Score]
      ,[Digital_Score]
      ,[Satisfaction_Score]
      ,[Performance_Score]
      ,[Audit_Score]
  FROM [ITU].[dbo].[01_Customer]